### ISSUE TITLE
Top3Things. Complete button not working

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#54] opened 2018-10-22 15:42 UTC
When a user wants to add Top3Thing:

they go to Top Three Things
they click Create button and see Create Top Three Things details on the right
they add 1-3 Top3Things and click Complete button
Should be: 1-3 changes to Top3Things have to be saved and shown in table

Bug: nothing happens when a user clicks Complete button: https://www.screencast.com/t/aMFkQf7eiXJJ

Assume that problem is in server response:
https://www.screencast.com/t/OXaIpC7u3nA

Bogdan commented:
@kuvakina
Alexandra, could you please add screenshots with Network/Headers tab?
It is necessary to see text of request to server

Tony commented:
yes, this needs more detail on server request/response please

Alexandra commented:
yes, see below, please:
https://www.screencast.com/t/2TLfpwrP6w

**Comment by PhilBarrett** [comment] 2018-10-31 09:59
![Screen Shot 2018-10-31 at 09.59.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a378e60c2e58415f47be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc58ff4ce84453a3103562f43b.png)

@Alena1508 can you take a look at this please

**Comment by Alena1508** [comment] 2018-10-31 14:36
@PhilBarrett 

I've checked it on my local machine and on dev (8000) and complete button working. I can't check functionality of this button on staging, because I have to look in the code.

But still, as Alexandra showed on screens above, I think it's a wrong response from server.

**Comment by PhilBarrett** [comment] 2018-11-01 11:14
Checked on Staging and working as intended. Closing this issue for now

**Closed by PhilBarrett** 2018-11-01 11:14 UTC
Labels: High Priority, PulseTile, bug, to do
