### ISSUE TITLE
Date of Birth error in Profile

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#42] opened 2018-10-04 17:01 UTC
see image below

**Comment by tony-shannon** [comment] 2018-10-04 17:04
![i591^pimgpsh_thumbnail_win_distr.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bae28b4d734ec0013e1f936/125516c66e82c728ace21e0d46e1c1c372bc93a082eeaf50ac62e49c3c4b257d280daf14678ced17bb4b68151d4d52be011a001ea9aacd39aca43922db0f5eeed43b5826956c14f8b88216bc54b323de1980a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59a43ce5ff44de24b53a411242e.jpg)

**Comment by PhilBarrett** [comment] 2018-10-08 13:14
@simongamester , can we have an update on this here please, cheers.

**Comment by tony-shannon** [comment] 2018-10-09 16:04
@simongamester 
yes there is a user DOB available
Please check with @robtweed  for details

**Comment by robtweed** [comment] 2018-10-09 16:43
Simon - I don't know what system you've used, but you've logged in in IDCR mode, so it won't be the Helm PHR system.  A PHR user gets their Date of Birth from the OpenId Connect Server, and it is definitely included.  The IDCR mechanism for login is not yet included in the Helm PHR

**Comment by simongamester** [comment] 2018-10-11 10:34
Suggest to hide this in the short term until DOB added to User API call.

**Comment by BogdanScherban** [comment] 2018-10-12 14:01
Task is fixed. 

What was updated:

1) Changed function which return the date: now we use the same one, which return correct date in other tables (it was checked by Timestamp converter: https://www.unixtimestamp.com/index.php)

2) Added condiction: if user birthdate is absent, we don't output it generally

**Comment by PhilBarrett** [comment] 2018-10-22 16:02
Working as intended on Dev, will await latest PT build on Staging

**Comment by PhilBarrett** [comment] 2018-10-31 10:35
Closed in error. Still seeing DOB in profile on staging

**Comment by kuvakina** [comment] 2018-11-01 17:31
@PhilBarrett you mean this date: https://www.screencast.com/t/YMijILkuy ?

**Comment by PhilBarrett** [comment] 2018-11-01 17:43
@kuvakina https://www.screencast.com/t/kZOjC9ayQb2 needs to be hidden please.

**Comment by kuvakina** [comment] 2018-11-05 16:14
@PhilBarrett We hid the date.

**Comment by kuvakina** [comment] 2018-11-05 16:14
@PhilBarrett We hid the date.

**Comment by kuvakina** [comment] 2018-11-22 13:16
@PhilBarrett @tony-shannon 

DOB there is still hidden.

**Closed** 2018-11-22 14:54 UTC
Labels: 3 - Review, High Priority, PulseTile
