### ISSUE TITLE
Helm-Staging bugs

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#123] opened 2019-04-11 11:41 UTC
- [x] Author is showing as Null Null https://www.screencast.com/t/WoR5WujQHtc
- [x] Helm-Dev shows top 3 things (https://www.screencast.com/t/CJtbVtBRzeN), Helm Staging shows problems/issues (https://www.screencast.com/t/XdyS23LCIgjd)
- [x] The user tour is out of sync and you can't go back https://www.screencast.com/t/bcGHsVpazfpa
- [x] Helm URL - no nhs#- by design ?

**Comment by PhilBarrett** [comment] 2019-04-11 16:38
Moving to review for final check in Staging before closing. Helm URL to be checked as well

**Comment by tony-shannon** [comment] 2019-04-15 09:13
this is relevant to the author null null issue
![image_2019_04_12T15_40_44_084Z.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bae28b4d734ec0013e1f936/125516c66e82c728ace21e0d46e1999b2487bcfbdfb8e67cf409cfc57b7276261650f31424d1dc78e7164143434d0eee1e020a17b8eb8339a3e46d23df5f0ebbd63f0c25c36911acb1814ab602ef768e5d99a4fedb1294b7607caddecd5d340c071883fe5830a59a4ac15ef743e74557b65e.png)

**Comment by BogdanScherban** [comment] 2019-04-15 11:09
@tony-shannon @robtweed 
This logic is used in current version. Look, please, at rows 23-31:
https://github.com/PulseTile/PulseTile-RA/blob/627800b64598fad3688a6db5d29eaab5a8fec6b0/src/core/dataProviders/authProvider.js#L23

Null Null can occurs only if **firstName** and **lastName** are absent.

**Comment by robtweed** [comment] 2019-04-15 11:55
The problem is you are doing this:
const userName = get(decodeToken, 'openid.firstName', null) + ' ' + get(decodeToken, 'openid.lastName', null);

instead of

const userName = get(decodeToken, 'firstName', null) + ' ' + get(decodeToken, 'lastName', null);

**Comment by BogdanScherban** [comment] 2019-04-15 12:24
@robtweed 
Is it only for Staging?
Because, for example, at London get(decodeToken, 'firstName', null) return null

**Comment by robtweed** [comment] 2019-04-15 12:45
Yes the change is currently only on Staging.  Probably a good idea to modify the code to work in either environment for now.  Helm-dev and London need to have the necessary changes made to the OIDC-Client / authentication_service microservice which will be something I can assist with in a few days

**Comment by PhilBarrett** [comment] 2019-04-15 15:20
Tested and working fine on Staging, thanks all

**Closed** 2019-04-17 07:28 UTC
Labels: 3 - Review, Helm, bug
