### ISSUE TITLE
Helm E2E tests failure

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#62] opened 2018-10-26 16:24 UTC
although tests were updated, for some reason:

Most of the tests fail on Remote machine : https://www.screencast.com/t/UL8Ov43V

patientAccordionTest and patientInformationTest fail on Jenkins (we had the same problem with React tests before): https://www.screencast.com/t/iges2cZXb

We thought it can be because we run out of memory (not the reason) or we again have a miner (also not the reason).

On local machine Helm test run successfully.

We'll look further into it on Monday. Also check other tests on Remote machine (on Jenkins all tests work except Helm test).

**Comment by kuvakina** [comment] 2018-11-06 14:16
@tony-shannon @PhilBarrett 

As we hid the page user shouldn't see in Helm PHR (#66 https://waffle.io/RippleOSI/combined-development-view/cards/5be17d71657a7d00ed970b09 ), we updated tests for Helm also and now E2E test on Jenkins and remote machine pass successfully:

RM: https://www.screencast.com/t/6Xdx3teQ

**Comment by PhilBarrett** [comment] 2018-11-06 15:38
Great news, thank you @kuvakina . Do you know what would need to happen to resolve it, when we bring the profile back at a later stage. If you can document that here please, we can close it down. Thanks

**Comment by kuvakina** [comment] 2018-11-22 13:14
React E2E tests failed in Jenkins because of malware. But we cleaned server from malware and changed passwords on Jenkins for all users (I sent new passwords on your emails).

Now React tests passes in both Jenkins & RM.

@tony-shannon @PhilBarrett

**Comment by PhilBarrett** [comment] 2018-11-22 14:56
@kuvakina do you have an update on my earlier point you can add here please, before we close this issue. Thanks

**Comment by kuvakina** [comment] 2018-11-22 15:29
@PhilBarrett We can't tell where was the error with that two tests. 

We can check it, but for this, we have to return the tests and re-build :8000. Then we can try to find the issue. 

Should we do this?

**Comment by tony-shannon** [comment] 2019-02-18 13:40
E2E tests need revisiting and updating please

**Comment by PhilBarrett** [comment] 2019-03-19 16:08
Duplicate of https://github.com/LeedsCC/Helm-PHR-Project/issues/86 -  closing out

**Closed by PhilBarrett** 2019-03-19 16:08 UTC
Labels: Helm, Medium Priority, PulseTile-R, bug, to do
